add solution for dz3 2-task
js-tasks-ru/htmlcss-20230124_anton-elshin pull request #10
Opened 2023-02-12 20:38 UTC by AntonElshin

2023-02-12 20:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-14 07:19 UTC, GSemikozov requested changes

2023-02-14 07:19 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +          <div class='modal__button' id='modal-close'>
`<button>`

2023-02-14 07:19 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +          <h1 class='modal__title'>Modal title</h1>
h4

2023-02-14 07:19 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    min-width: 508px;
растягиваем на 100% ширины и высоты

2023-02-14 07:19 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    top: 50%;
см выше

2023-02-14 07:19 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__content {
а вот этот элемент надо выравнивать по середине либо через родителя либо через absolute

2023-02-14 07:19 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__button {
расположит абсолютом, и тогда 2 указанных свойства будут лишними

2023-02-14 07:49 UTC, AntonElshin commented on 05-lection3/02-modal/index.html
> +          <h1 class='modal__title'>Modal title</h1>
исправил

2023-02-14 08:56 UTC, AntonElshin commented on 05-lection3/02-modal/index.html
> +          <div class='modal__button' id='modal-close'>
исправил

2023-02-14 09:25 UTC, AntonElshin commented on 05-lection3/02-modal/modal.css
> +.modal__button {
сделал по другому. Абсолютом не получилось, потому что при изменении размеров экрана сложно оставить крестик в правом верхнем углу.

2023-02-14 09:32 UTC, AntonElshin commented on 05-lection3/02-modal/modal.css
> +.modal__content {
исправил

2023-02-14 09:48 UTC, AntonElshin commented on 05-lection3/02-modal/modal.css
> +    top: 50%;
исправил

2023-02-14 09:48 UTC, AntonElshin commented on 05-lection3/02-modal/modal.css
> +    min-width: 508px;
исправил

2023-02-14 12:10 UTC, GSemikozov requested changes

2023-02-14 12:10 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__button {
наоборот легко) просто задать родителю относительно которого позиционируем - position: relative

2023-02-14 12:10 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: relative;
блок должен позиционироваться как fixed и растягиваться на всю ширину и высоту вьюпорта

2023-02-15 08:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-15 08:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-15 08:24 UTC, AntonElshin commented on 05-lection3/02-modal/modal.css
> +.modal__button {
переделал так, left: calc(100% - 20px);

2023-02-15 08:45 UTC, AntonElshin commented on 05-lection3/02-modal/modal.css
> +    position: relative;
поправил

2023-02-15 09:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-15 21:15 UTC, GSemikozov approved these changes

2023-02-15 21:15 UTC, merged