Dz3/01 tooltip
js-tasks-ru/htmlcss-20230124_anton-elshin pull request #11
Opened 2023-02-12 21:52 UTC by AntonElshin

2023-02-12 21:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-14 07:20 UTC, GSemikozov requested changes

2023-02-14 07:20 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    top: calc(-170% - 8px);
чтобы вручную не высчитывать привязываясь к размерам триггера, лучше bottom: calc(100% + 8px)

2023-02-14 07:43 UTC, AntonElshin commented on 05-lection3/01-tooltip/tooltip.css
> +    top: calc(-170% - 8px);
исправил

2023-02-14 12:10 UTC, GSemikozov approved these changes

2023-02-14 12:10 UTC, merged