Dz5/02 radio
js-tasks-ru/htmlcss-20230124_anton-elshin pull request #18
Opened 2023-02-20 21:36 UTC by AntonElshin

2023-02-20 21:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-21 10:46 UTC, GSemikozov requested changes

2023-02-21 10:46 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    height: 28px;
удалим

2023-02-21 11:36 UTC, AntonElshin commented on 07-lection5/02-radio/radio.css
> +    height: 28px;
поправил

2023-02-21 15:18 UTC, GSemikozov approved these changes

2023-02-21 15:18 UTC, merged