Dz5/05 tabs
js-tasks-ru/htmlcss-20230124_anton-elshin pull request #21
Opened 2023-03-27 11:15 UTC by AntonElshin

2023-03-27 11:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-27 11:27 UTC, GSemikozov requested changes

2023-03-27 11:27 UTC, GSemikozov commented on 07-lection5/05-tabs/tabs.css
> +    max-width: 500px;
лишнее ограничение

2023-03-27 11:27 UTC, GSemikozov commented on 07-lection5/05-tabs/tabs.css
> +    display: none;
если так скрывать, то переключение недоступно с клавиатуры

2023-03-27 11:27 UTC, GSemikozov commented on 07-lection5/05-tabs/tabs.css
> +    display: flex;
не хватает overflow-x: auto

2023-03-27 11:27 UTC, GSemikozov commented on 07-lection5/05-tabs/tabs.css
> +.tabs__content {
а какой механизм переключения табов?

2023-03-27 11:27 UTC, GSemikozov commented on components/header/header.css
> +    margin-right: 568px;
лишнее - мы ведь контент складываем в container, зачем такой отступ?

2023-03-27 11:27 UTC, GSemikozov commented on components/navigation/navigation.css
> +    width: 252px;
фиксировать ширину не нужно

2023-03-27 11:27 UTC, GSemikozov commented on components/navigation/navigation.css
> +    margin-right: 56px;
точно ли это надо? даже если  да - на уровне блока марджины не задаем)

2023-03-27 11:27 UTC, GSemikozov commented on components/navigation/navigation.css
> +    width: 450px;
лишнее ограничение

2023-03-27 11:27 UTC, GSemikozov commented on components/navigation/navigation.css
> +    min-height: 24px;
лишнее

2023-03-27 13:25 UTC, AntonElshin commented on 07-lection5/05-tabs/tabs.css
> +    max-width: 500px;
исправил

2023-03-27 13:28 UTC, AntonElshin commented on 07-lection5/05-tabs/tabs.css
> +    display: flex;
добавил

2023-03-27 13:30 UTC, AntonElshin commented on components/navigation/navigation.css
> +    width: 252px;
исправил

2023-03-27 13:31 UTC, AntonElshin commented on components/navigation/navigation.css
> +    margin-right: 56px;
убрал

2023-03-27 13:33 UTC, AntonElshin commented on components/navigation/navigation.css
> +    min-height: 24px;
убрал

2023-03-27 13:33 UTC, AntonElshin commented on components/navigation/navigation.css
> +    width: 450px;
убрал

2023-03-27 13:35 UTC, AntonElshin commented on components/header/header.css
> +    margin-right: 568px;
сделал space-between у контейнера

2023-03-27 14:43 UTC, AntonElshin commented on 07-lection5/05-tabs/tabs.css
> +.tabs__content {
стрелками на клавиатуре, убрал display: none

2023-03-27 14:43 UTC, AntonElshin commented on 07-lection5/05-tabs/tabs.css
> +    display: none;
убрал

2023-03-27 14:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-04 20:24 UTC, GSemikozov approved these changes

2023-04-04 20:24 UTC, merged