Dz1/02 accordion
js-tasks-ru/htmlcss-20230124_anton-elshin pull request #5
Opened 2023-02-02 07:14 UTC by AntonElshin

2023-02-02 07:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-03 09:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-03 09:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-03 09:45 UTC, GSemikozov requested changes

2023-02-03 09:45 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  min-width: 731px;
лишнее

2023-02-03 09:45 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <ul class='accordion__list'>
на списке делать не надо, удалим

2023-02-03 09:45 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +          <li class='accordion__item'>
и тогда accordion__details - это и есть accordion__item (оставить один класс)

2023-02-03 09:45 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +          <li class='accordion__item'>
все айтемы аккордиона должны быть завернуты в div c классом блока .accordion

2023-02-03 09:45 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        .accordion__list {
23-39 - это же стили блока? почему они не в соответствующем файле?)

2023-02-03 12:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-03 14:04 UTC, GSemikozov requested changes

2023-02-03 14:04 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  min-width: 731px;
лишнее

2023-02-03 14:04 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  min-width: 650px;
лишнее

2023-02-03 14:04 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        .accordion__list {
все еще актуально

2023-02-03 14:09 UTC, GSemikozov requested changes

2023-02-03 14:09 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary {
при accordion__details[open] паддинг снизу будет другим (см макет)

2023-02-03 14:09 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +              <p class='accordion__text'>
контентом может быть все что угодно, так что <p> -> <div>

2023-02-03 14:15 UTC, AntonElshin commented on 03-lection1/02-accordion/index.html
> +        <ul class='accordion__list'>
удалил лист

2023-02-03 14:19 UTC, AntonElshin commented on 03-lection1/02-accordion/accordion.css
> +  min-width: 731px;
удалил

2023-02-03 14:20 UTC, AntonElshin commented on 03-lection1/02-accordion/accordion.css
> +  min-width: 650px;
удалил

2023-02-03 14:22 UTC, AntonElshin commented on 03-lection1/02-accordion/index.html
> +        .accordion__list {
перенёс

2023-02-03 14:22 UTC, AntonElshin commented on 03-lection1/02-accordion/index.html
> +          <li class='accordion__item'>
переделал

2023-02-03 14:29 UTC, AntonElshin commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary {
исправил, нужно мне быть внимательнее

2023-02-03 14:56 UTC, AntonElshin commented on 03-lection1/02-accordion/index.html
> +              <p class='accordion__text'>
переделал на div и дал более общее название классу

2023-02-03 14:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-03 15:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-03 15:41 UTC, GSemikozov requested changes

2023-02-03 15:41 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  display: none;
+ list-style: none

2023-02-03 15:41 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +          <details class='accordion__details'>
все секции должны быть завернуты в один общий div (поскольку у нас 1 аккордион, и у него 3 секции)

2023-02-03 15:41 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  margin-bottom: 8px;
1. марджины на уровне блока не задаем
2. отступ нужен будет между секциями, а не между блоками

2023-02-03 15:41 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion:first-child {
лишнее, удалим

2023-02-03 15:41 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion:last-child {
лишнее, удалим

2023-02-04 23:39 UTC, AntonElshin commented on 03-lection1/02-accordion/accordion.css
> +  display: none;
исправлено

2023-02-04 23:40 UTC, AntonElshin commented on 03-lection1/02-accordion/index.html
> +          <details class='accordion__details'>
исправлено

2023-02-04 23:42 UTC, AntonElshin commented on 03-lection1/02-accordion/accordion.css
> +  margin-bottom: 8px;
исправлено, перенёс отступ в accordion__details

2023-02-04 23:43 UTC, AntonElshin commented on 03-lection1/02-accordion/accordion.css
> +.accordion:first-child {
удалил

2023-02-04 23:43 UTC, AntonElshin commented on 03-lection1/02-accordion/accordion.css
> +.accordion:last-child {
удалил

2023-02-04 23:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-04 23:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-06 11:03 UTC, GSemikozov approved these changes

2023-02-06 11:03 UTC, merged