add solution for dz2 3-task
js-tasks-ru/htmlcss-20230124_anton-elshin pull request #6
Opened 2023-02-05 13:31 UTC by AntonElshin

2023-02-05 13:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-06 11:06 UTC, GSemikozov requested changes

2023-02-06 11:06 UTC, GSemikozov commented on index.html
> +      .preview {
должно быть описано как отдельный блок в components

2023-02-06 11:06 UTC, GSemikozov commented on index.html
> +        padding-top: 68px;
паддинги - свойства блока

2023-02-06 11:06 UTC, GSemikozov commented on index.html
> +      .cards {
лишний блок - карточки будут лежать в: .preview -> .container -> .preview__container (этот контейнер и будет display: flex)

2023-02-06 11:06 UTC, GSemikozov commented on index.html
> +      .card {
отдельный блок в components

2023-02-06 15:31 UTC, AntonElshin commented on index.html
> +      .preview {
исправил

2023-02-06 15:31 UTC, AntonElshin commented on index.html
> +        padding-top: 68px;
исправил

2023-02-06 15:31 UTC, AntonElshin commented on index.html
> +      .cards {
исправил

2023-02-06 15:31 UTC, AntonElshin commented on index.html
> +      .card {
исправил

2023-02-07 10:04 UTC, GSemikozov requested changes

2023-02-07 10:04 UTC, GSemikozov commented on components/preview/preview.css
> +  width: 1110px;
в разметке этот контейнер уже лежит в общем контейнере, так что ограничивать по ширине не надо, и высоту фиксировать тоже не стоит. Ну и justify-content + align-content тоже не нужны

2023-02-07 11:20 UTC, AntonElshin commented on components/preview/preview.css
> +  width: 1110px;
убрал свойства. Теперь до появления новой карточки отсуп справа и слева будет отличаться. Пока нет идей, как это исправить.

2023-02-08 21:21 UTC, GSemikozov commented on components/preview/preview.css
> +  width: 1110px;
не совсем понял из коммента в чем проблема, но - по стилям все правильно, отступы между карточками регулируется через gap

2023-02-08 21:21 UTC, GSemikozov approved these changes

2023-02-08 21:21 UTC, merged