Dz3/04 component page
js-tasks-ru/htmlcss-20230124_anton-elshin pull request #9
Opened 2023-02-12 18:52 UTC by AntonElshin

2023-02-12 18:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-14 07:10 UTC, GSemikozov requested changes

2023-02-14 07:10 UTC, GSemikozov commented on components/template/template.css
> +.page {
описывать все блоки в одном файле не надо) принцип такой же как и при верстке Главной - собираем из блоков. Поэтому - нужно разнести все блоки по файлам

2023-02-14 07:10 UTC, GSemikozov commented on components/template/template.css
> +    margin: 36px 56px auto 165px;
лишние марджины - на уровне блока не задаем

2023-02-14 07:10 UTC, GSemikozov commented on components/template/template.css
> +    margin-right: 165px;
точно будет лишним - блоки будут завернуты в container

2023-02-14 07:10 UTC, GSemikozov commented on components/template/template.css
> +    min-width: 825px;
лишнее

2023-02-14 07:10 UTC, GSemikozov commented on components/template/template.css
> +.component_container {
лишнее) лучше на родителе паддинг

2023-02-14 07:10 UTC, GSemikozov commented on components/template/template.css
> +.component_title {
если это элемент блока то .component__title

2023-02-14 07:10 UTC, GSemikozov commented on components/template/template.css
> +.container_histogram {
контейнер ничего не знает про то что в него вставляют) под каждый вставляемый блок не напасемся модификаторов + это не гибко.

2023-02-14 07:10 UTC, GSemikozov commented on components/template/template.css
> +    width: 1440px;
лишнее ограничение

2023-02-14 07:10 UTC, GSemikozov commented on components/template/template.css
> +    min-height: 130px;
и это

2023-02-14 07:10 UTC, GSemikozov commented on components/template/template.css
> +.footer__title_template {
.footer_template .footer__title {}

2023-02-14 07:10 UTC, GSemikozov commented on components/template/template.css
> +    max-width: 209px;
лишнее

2023-02-14 10:35 UTC, AntonElshin commented on components/template/template.css
> +.page {
исправлено

2023-02-14 10:39 UTC, AntonElshin commented on components/template/template.css
> +    margin: 36px 56px auto 165px;
исправил

2023-02-14 11:38 UTC, AntonElshin commented on components/template/template.css
> +    margin-right: 165px;
исправлено

2023-02-14 11:43 UTC, AntonElshin commented on components/template/template.css
> +    min-width: 825px;
исправил

2023-02-14 11:43 UTC, AntonElshin commented on components/template/template.css
> +    margin-right: 165px;
исправил

2023-02-14 11:46 UTC, AntonElshin commented on components/template/template.css
> +.component_container {
исправил

2023-02-14 11:46 UTC, AntonElshin commented on components/template/template.css
> +.component_title {
исправил

2023-02-14 11:50 UTC, AntonElshin commented on components/template/template.css
> +.container_histogram {
исправил

2023-02-14 11:51 UTC, AntonElshin commented on components/template/template.css
> +    width: 1440px;
исправил

2023-02-14 11:52 UTC, AntonElshin commented on components/template/template.css
> +    min-height: 130px;
исправил

2023-02-14 11:53 UTC, AntonElshin commented on components/template/template.css
> +.footer__title_template {
исправил

2023-02-14 11:56 UTC, AntonElshin commented on components/template/template.css
> +    max-width: 209px;
исправил

2023-02-14 12:07 UTC, GSemikozov approved these changes

2023-02-14 12:08 UTC, merged